plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-sass-converter
  - jekyll-feed

permalink: "/:categories/:title"

newsletter_url: //goo.gl/forms/2uB1EuoBpT8fYsCB2

greenlight_url: //steamcommunity.com/sharedfiles/filedetails/?id=924842091

js: { integrity: true } 

sass:
  style: compressed
  sass_dir: _sass

new_version_available_texts:
  - "v$1 has arrived!"
  - "v$1 is available!"
  - "v$1 is here!"

description: >-
  Voxel Tycoon - a tycoon strategy game about transportation, factories, and mining infinite voxel landscapes.
  
  Inspired by the most notable transport games in history, expanded with all-new features never before seen in the genre.